name: Build and Deploy

on:
  issues:
    types: [opened, edited, deleted]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        python3 make_title.py
        mkdir out
        mv index.html out/index.html
        mv pages out

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'